# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main_right:
  - name: About
    url: tour
    weight: 10
  #  - name: News
  #    url: post
  #    weight: 20
  # - name: People
  #   url: people
  #   weight: 30
  - name: Talks
    url: event
    weight: 20
  # - name: Publications
  #   url: publication
  #   weight: 50
#  - name: Contact
#    identifier: contact
#    #    url: contact
#    weight: 60
  - name: Recommend a Speaker
#    parent: contact
    url: https://forms.office.com/r/NWevdcfcMF
    target: "_blank"
    weight: 30
    post: '&nbsp;<i class="fa fa-external-link" aria-hidden="true" style="color: gray; font-size: 0.8em;"></i>'
  - name: Feedback
#    parent: contact
    url: https://forms.office.com/r/yt91ENZmuF
    target: "_blank"
    weight: 40
    post: '&nbsp;<i class="fa fa-external-link" aria-hidden="true" style="color: gray; font-size: 0.8em;"></i>'

